.mode csv
.separator |
DROP TABLE IF EXISTS DIST_POP;
CREATE TABLE dist_pop(
  "state" char(2),
  "district_id" int,
  "district name" varchar(200),
  "population" long
);

.import data/dist_pop.txt dist_pop
DELETE FROM dist_pop LIMIT 1;

DROP TABLE IF EXISTS candidate;
CREATE TABLE candidate(
  "CAND_ID" VARCHAR(9),
  "CAND_NAME" VARCHAR(200),
  "CAND_PTY_AFFILIATION" VARCHAR(3),
  "CAND_ELECTION_YR" INT,
  "CAND_OFFICE_ST" VARCHAR(2),
  "CAND_OFFICE" VARCHAR(1),
  "CAND_OFFICE_DISTRICT" INT,
  "CAND_ICI" VARCHAR(1),
  "CAND_STATUS" VARCHAR(1),
  "CAND_PCC" VARCHAR(9),
  "CAND_ST1" VARCHAR(34),
  "CAND_ST2" VARCHAR(34),
  "CAND_CITY" VARCHAR(30),
  "CAND_ST" VARCHAR(2),
  "CAND_ZIP" VARCHAR(9)
);
.import data/candidate.txt candidate
DELETE FROM candidate LIMIT 1;

DROP TABLE IF EXISTS COMMITTEE;

CREATE TABLE committee(
  "CMTE_ID" VARCHAR(9),
  "CMTE_NM" VARCHAR(200),
  "TRES_NM" VARCHAR(90),
  "CMTE_ST1" VARCHAR(34),
  "CMTE_ST2" VARCHAR(34),
  "CMTE_CITY" VARCHAR(30),
  "CMTE_ST" VARCHAR(2),
  "CMTE_ZIP" VARCHAR(9),
  "CMTE_DSGN" VARCHAR(1),
  "CMTE_TP" VARCHAR(1),
  "CMTE_PTY_AFFILIATION" VARCHAR(3),
  "CMTE_FILING_FREQ" VARCHAR(1),
  "ORG_TP" VARCHAR(1),
  "CONNECTED_ORG_NM" VARCHAR(200),
  "CAND_ID" VARCHAR(9)
);

.import data/committee.txt committee
DELETE FROM committee LIMIT 1;

DROP TABLE IF EXISTS PAC_SUMMARY;

CREATE TABLE pac_summary(
  "CMTE_ID" VARCHAR(9),
  "CMTE_NM" VARCHAR(200),
  "CMTE_TP" VARCHAR(1),
  "CMTE_DSGN" VARCHAR(1),
  "CMTE_FILING_FREQ" VARCHAR(1),
  "TTL_RECEIPTS" FLOAT,
  "TRANS_FROM_AFF" FLOAT,
  "INDIV_CONTRIB" FLOAT,
  "OTHER_POL_CMTE_CONTRIB" FLOAT,
  "CAND_CONTRIB" FLOAT,
  "CAND_LOANS" FLOAT,
  "TTL_LOANS_RECEIVED" FLOAT,
  "TTP_DISB" FLOAT,
  "TRANSF_TO_AFF" FLOAT,
  "INDV_REFUNDS" FLOAT,
  "OTHER_POL_CMTE_REFUNDS" FLOAT,
  "CAND_LOAN_REPAY" FLOAT,
  "LOAN_REPAY" FLOAT,
  "COH_BOP" FLOAT,
  "COH_COP" FLOAT,
  "DEBTS_OWED_BY" FLOAT,
  "NONFED_TRANS_RECEIVED" FLOAT,
  "CONTRIB_TO_OTHER_CMTE" FLOAT,
  "IND_EXP" FLOAT,
  "PTY_COORD_EXP" FLOAT,
  "NONFED_SHARE_EXP" FLOAT,
  "CVG_END_DT" DATE 
);

.import data/pac_summary.txt pac_summary
DELETE FROM pac_summary LIMIT 1;


DROP TABLE IF EXISTS cand_summary;
CREATE TABLE cand_summary (
  "CAND_ID" VARCHAR(9),
  "CAND_NAME" VARCHAR(200),
  "CAND_ICI" VARCHAR(1),
  "PTY_CD" VARCHAR(1),
  "PTY_AFFILIATION" VARCHAR(3),
  "TTL_RECEIPTS" FLOAT,
  "TRANS_FROM_AUTH" FLOAT,
  "TTL_DISB" FLOAT,
  "TRANS_TO_AUTH" FLOAT,
  "COH_BOP" FLOAT,
  "COH_COP" FLOAT,
  "CAND_CONTRIB" FLOAT,
  "CAND_LOANS" FLOAT,
  "OTHER_LOANS" FLOAT,
  "CAND_LOAN_REPAY" FLOAT,
  "OTHER_LOAN_REPAY" FLOAT,
  "DEBTS_OWED_BY" FLOAT,
  "TTL_INDIV_CONTRIB" FLOAT,
  "CAND_OFFICE_ST" FLOAT,
  "CAND_OFFICE_DISTRICT" FLOAT,
  "SPEC_ELECTION" FLOAT,
  "PRIM_ELECTION" FLOAT,
  "RUN_ELECTION" FLOAT,
  "GEN_ELECTION" FLOAT,
  "GEN_ELECTION_PERCENT" FLOAT,
  "OTHER_POL_CMTE_CONTRIB" FLOAT,
  "POL_PTY_CONTRIB" FLOAT,
  "CVG_END_DT" FLOAT,
  "INDIV_REFUNDS" FLOAT,
  "CMTE_REFUNDS" FLOAT);

.import data/cand_summary.txt cand_summary
DELETE FROM cand_summary LIMIT 1;
